# Generated by Django 3.2.5 on 2021-07-16 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_skillmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmodel',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.profilemodel', verbose_name='Profile'),
            preserve_default=False,
        ),
    ]
