# Generated by Django 3.2.5 on 2021-07-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skillmodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmodel',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Skill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='app.profilemodel', verbose_name='Profile'),
        ),
    ]
