# Generated by Django 3.2.5 on 2021-07-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_skillmodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillmodel',
            name='phone',
        ),
    ]
