# Generated by Django 3.2.5 on 2021-07-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_skillmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
