# Generated by Django 3.2.5 on 2021-07-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profilemodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='dob',
            field=models.DateField(default=None, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
