# Generated by Django 3.2.5 on 2021-07-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profilemodel_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
