# Generated by Django 3.2.5 on 2021-07-17 14:31

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_alter_profilemodel_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='country',
            field=models.CharField(default='', max_length=60, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='user',
            field=models.ForeignKey(default=app.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='profile',
            field=models.ForeignKey(default=app.models.get_default_profile, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='app.profilemodel', verbose_name='Profile'),
        ),
    ]
