# Generated by Django 3.2.5 on 2021-07-18 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210717_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='dob',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date of Birth'),
        ),
    ]
