# Generated by Django 3.2.5 on 2021-07-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_email_messagemodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='subject',
            field=models.CharField(blank=True, max_length=50, verbose_name='Subject'),
        ),
    ]
