# Generated by Django 3.2.5 on 2021-07-24 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_messagemodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
