# Generated by Django 3.2.5 on 2021-07-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_messagemodel_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_message_limit', models.IntegerField(default=3, verbose_name='Daily message limit per email address.')),
            ],
        ),
    ]
