# Generated by Django 3.2.5 on 2021-07-24 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='SettingsModel',
        ),
    ]
